title:              Scientist in City
email:              jirehbak@naver.com
description:        도시의 과학자
author:             JirehBak
baseurl:            
url:                "https://jirehbak.github.io"
category_dir:       category/

# Social Profiles
twitter_username:   
github_username:    jirehbak
facebook_username:  
instagram_username:  
linkedin_username:  jirehbak
brunch_username:  jirehpark

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-176062516-1 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
